before_script:
  - lsb_release -a
#  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
#  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - python --version
  - which python
#  - pip install virtualenv
  - python -m venv tmp_env
  - source tmp_env/bin/activate

stages:
  - Static Analysis
  - Test

pylint:
  stage: Static Analysis
  script:
  - pip install pylint
  - pylint mxmc

flake8:
  stage: Static Analysis
  script:
  - pip install flake8
  - flake8 mxmc/
  
pytest:
  stage: Test
  script:
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-mock
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - pytest --cov=mxmc --cov-report=term-missing tests/
