image: "python:3.7"

before_script:
  - python --version
  - which python
  - which docker
  - pip install -r requirements.txt

stages:
  - Static Analysis

pylint:
  stage: Static Analysis
  script:
  - pylint mxmc
