image: "python:3.7"

before_script:
  - apt-get install -y python3.7
  - python3 --version
  - which python3
  - pip install -r requirements.txt

stages:
  - Static Analysis

pylint:
  stage: Static Analysis
  script:
  - pylint mxmc
